/* The combined-spouse projection, pinned BEFORE the household-members rework.

   v2 profiles carry a single `spouse` block folded into the projection by
   `combineSpouse`. The rework replaces that with per-person ledgers, and the
   migration promises a combined spouse keeps the household numbers it had.
   This snapshot was generated by the pre-rework engine (commit 0b261d5) and
   is the reference that promise is checked against. Nothing here writes it:
   the engine that produced it is gone, which is the point. */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { runProjectionV1 } from "./projection.mjs";
import { computeSuccessScore } from "./successscore.mjs";
import { migrate } from "../profile/migrate.mjs";

const fixture = () => JSON.parse(
  readFileSync(new URL("./fixtures/v2-spouse-combined.json", import.meta.url)));
const snapUrl = new URL("./fixtures/v2-spouse-combined.snapshot.json", import.meta.url);

/* `year` follows today's date; see projection-v1.snapshot.test.mjs. */
const stripYear = (out) => ({ ...out, data: out.data.map(({ year, ...rest }) => rest) });

const scoreSummary = (s) => ({ score: s.score, band: s.band, corpus: s.corpus });

function run(plan) {
  return {
    projection: stripYear(runProjectionV1(plan)),
    successScore: scoreSummary(computeSuccessScore(plan)),
  };
}

/* Money is compared to the rupee: every figure in a row is already rounded,
   and it must not move at all. Unrounded floats — the blended return, peak net
   worth, the simulated corpus — are allowed float noise only: the per-person
   ledgers sum the same balances in a different order. */
const close = (a, b, rel) => Math.abs(a - b) <= rel * Math.max(1, Math.abs(b));

function assertRowsMatch(actual, expected) {
  assert.equal(actual.length, expected.length, "row count");
  actual.forEach((row, i) => {
    const want = expected[i];
    for (const [k, v] of Object.entries(want)) {
      const where = `age ${want.age}, ${k}`;
      if (k === "buckets") {
        for (const [b, amt] of Object.entries(v)) {
          assert.ok(Math.abs(row.buckets[b] - amt) <= 1, `${where}.${b}: ${row.buckets[b]} vs ${amt}`);
        }
      } else if (k === "blendedReturn" || k === "returnRate") {
        assert.ok(close(row[k], v, 1e-9), `${where}: ${row[k]} vs ${v}`);
      } else if (typeof v === "number") {
        assert.ok(Math.abs(row[k] - v) <= 1, `${where}: ${row[k]} vs ${v}`);
      } else {
        assert.equal(row[k], v, where);
      }
    }
  });
}

test("v2 combined spouse: migrated to a member, the household projection does not move", () => {
  const want = JSON.parse(readFileSync(snapUrl));
  const got = run(migrate(fixture()));

  assertRowsMatch(got.projection.data, want.projection.data);
  for (const k of ["fiAge", "fiAgeSustained", "depletionAge", "openingPortfolio"]) {
    assert.equal(got.projection[k], want.projection[k], k);
  }
  assert.ok(close(got.projection.peakNW, want.projection.peakNW, 1e-9), "peakNW");

  assert.equal(got.successScore.score, want.successScore.score, "score");
  assert.deepEqual(got.successScore.band, want.successScore.band, "band");
  for (const q of ["p10", "p50", "p90"]) {
    assert.ok(close(got.successScore.corpus[q], want.successScore.corpus[q], 1e-8), `corpus ${q}`);
  }
});

test("v2 combined spouse: the migrated plan carries them as one included member", () => {
  const m = migrate(fixture());
  assert.equal(m.members.length, 1);
  assert.equal(m.members[0].included, true);
  assert.equal(m.members[0].personal.fullName, "Priya");
  assert.ok(!("spouse" in m) && !("combineSpouse" in m));
});
