/* The combined-spouse projection, pinned BEFORE the household-members rework.

   v2 profiles carry a single `spouse` block folded into the projection by
   `combineSpouse`. The rework replaces that with per-person ledgers, and the
   migration promises a combined spouse keeps the household numbers it had.
   This snapshot was generated by the pre-rework engine and is the reference
   that promise is checked against — regenerate it only with that engine.

   UPDATE_SNAPSHOTS=1 npm test   rewrites it; review the diff line by line. */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { runProjectionV1 } from "./projection.mjs";
import { computeSuccessScore } from "./successscore.mjs";

const fixture = () => JSON.parse(
  readFileSync(new URL("./fixtures/v2-spouse-combined.json", import.meta.url)));
const snapUrl = new URL("./fixtures/v2-spouse-combined.snapshot.json", import.meta.url);

/* `year` follows today's date; see projection-v1.snapshot.test.mjs. */
const stripYear = (out) => ({ ...out, data: out.data.map(({ year, ...rest }) => rest) });

const scoreSummary = (s) => ({ score: s.score, band: s.band, corpus: s.corpus });

function run(plan) {
  return {
    projection: stripYear(runProjectionV1(plan)),
    successScore: scoreSummary(computeSuccessScore(plan)),
  };
}

test("v2 combined spouse: projection and score match the pre-rework engine", () => {
  const out = run(fixture());
  if (process.env.UPDATE_SNAPSHOTS) {
    writeFileSync(snapUrl, JSON.stringify(out, null, 2) + "\n");
    return;
  }
  assert.ok(existsSync(snapUrl), "snapshot missing; run UPDATE_SNAPSHOTS=1 npm test");
  assert.deepEqual(out, JSON.parse(readFileSync(snapUrl)));
});
